use crate::format::path_text;
use crate::spool::ResultSpool;
use anyhow::Result;
use std::io::Write;

pub fn write(spool: &mut ResultSpool, writer: &mut dyn Write) -> Result<()> {
    writeln!(writer, "%%%% HASHDEEP-1.0")?;
    write!(writer, "%%%% size")?;
    for algorithm in spool.algorithms() {
        write!(writer, ",{}", algorithm.slug())?;
    }
    writeln!(writer, ",filename")?;
    writeln!(
        writer,
        "## Generated by VeriHash {}",
        env!("CARGO_PKG_VERSION")
    )?;
    writeln!(writer, "##")?;
    spool.for_each_record(|record| {
        write!(writer, "{}", record.size)?;
        for (_, digest) in record.hashes {
            write!(writer, ",{}", digest.to_hex())?;
        }
        write!(writer, ",")?;
        write_csv_field(writer, &path_text(&record.relative))?;
        writeln!(writer)?;
        Ok(())
    })
}

fn write_csv_field(writer: &mut dyn Write, value: &str) -> Result<()> {
    if value.contains([',', '"', '\n', '\r']) {
        write!(writer, "\"")?;
        for character in value.chars() {
            if character == '"' {
                write!(writer, "\"\"")?;
            } else {
                write!(writer, "{character}")?;
            }
        }
        write!(writer, "\"")?;
    } else {
        write!(writer, "{value}")?;
    }
    Ok(())
}
